[package]
name = "kms"
version = "0.1.0"
authors = ["The Attestation Agent Authors"]
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
crypto = { path = "../crypto", default-features = false, optional = true}
hkdf = { version = "0.12.3", optional = true }
rand = { version = "0.8.4", optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
sha2 = { version = "0.10.6", optional = true }
strum.workspace = true
tokio = "1.0"
uuid = { version = "1.3.0", features = ["fast-rng", "v4"], optional = true }
zeroize = { version = "1.6.0", optional = true }

chrono = "0.4.26"
reqwest = { version = "0.11", features = ["blocking", "json"] }
hex = "0.4.3"
base64 = "0.12.1"
pem = "2.0.1"
prost = { version = "0.11" }
tonic = { version = "0.9" }
openssl = "0.10.54"
lazy_static = "1.4.0"

[dev-dependencies]
rstest.workspace = true
tokio = { version = "1.0", features = ["rt", "macros" ] }

[build-dependencies]
anyhow = "1"
tonic-build = { version = "0.8" }

[features]
default = [ "sample-rust" ]

sample = [ "zeroize", "rand", "uuid", "hkdf", "sha2", "serde_json", "serde" ]
sample-openssl = [ "crypto/openssl", "sample" ]
sample-rust = [ "crypto/rust-crypto", "sample" ]
