name: EAA kbc build CI
on:
  push:
    paths:
      - 'src/kbc_modules/eaa_kbc/**'
      - '.github/workflows/eaa_kbc.yml'
  pull_request:
    paths:
      - 'src/kbc_modules/eaa_kbc/**'
      - '.github/workflows/eaa_kbc.yml'
  create:
    paths:
      - 'src/kbc_modules/eaa_kbc/**'

jobs:
  eaa_kbc_ci:
    if: github.event_name == 'pull_request'
    name: Check
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable

    container: runetest/compilation-testing:ubuntu20.04
          
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Rust toolchain
        run: |
          apt-get update && apt-get install -y cargo
          cp -r /root/.cargo /github/home/.cargo
          rustup install stable
          rustup default stable

      - name: Build and install rats-tls
        run: | 
          curl -L https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | apt-key add -
          echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu focal main' | tee /etc/apt/sources.list.d/intel-sgx.list
          apt-get update
          apt install -y libsgx-dcap-ql-dev libcurl4-openssl-dev
          git clone https://github.com/inclavare-containers/rats-tls
          cd rats-tls
          git reset --hard 2378719
          cmake -DBUILD_SAMPLES=on -H. -Bbuild
          make -C build install
      
      - name: Build AA with EAA KBC
        run: |
          make KBC=eaa_kbc && make install