name: Cut Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release number in semvar, e.g. "0.1.0"'
        required: true

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      -
        name: Build and push coco-key-provider
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.keyprovider
          platforms: linux/amd64
          push: true
          tags: ghcr.io/confidential-containers/coco-keyprovider:v${{ inputs.version }}, ghcr.io/confidential-containers/coco-keyprovider:latest
